export const REQUESTS_USERS_LOADING = "REQUESTS_USERS_LOADING";
export const REQUESTS_USERS_SUCCESS = "REQUESTS_USERS_SUCCESS";
export const REQUESTS_USERS_UPDATE = "REQUESTS_USERS_UPDATE";
export const REQUESTS_USERS_FAILURE = "REQUESTS_USERS_FAILURE";